### ISSUE TITLE
データサイエンスの流れをyoutubeで勉強した

### ISSUE THREAD

**Issue by mokroke** [ycu-engine/community#10]
# TL;DR
はやたすさんの「python×データサイエンス入門」をみながらやりました。

# 内容
kaggleのタイタニック号のチュートリアルでデータの前処理から決定木までデータ分析の一通りの流れを実際にやってみました。
# 参考資料
https://youtu.be/F3D75T_wW4w

**Comment by YutaUra** [comment]
データアナリティスをしっかりやってていいと思います！
