### ISSUE TITLE
【Python】os.environ で KeyErrorが発生

### ISSUE THREAD

**Issue by mokroke** [ycu-engine/community#11]
# 困っていること

key errorの解消方法がわかりません

# 解決方法

※ 解決した場合に解決方法を記載する欄を用意しています。作成時は空で構いません。あとでみた人がぱっと見で解決方法がわかる状態にしましょう。

# 背景
データサイエンス100本ノック（構造化データ加工編）の「初めに実行するセル」を実行したときにkey errorが発生

# ソースコード
```python
pgconfig = {
    'host': 'db',
    'port': os.environ['PG_PORT'],
    'database': os.environ['PG_DATABASE'],
    'user': os.environ['PG_USER'],
    'password': os.environ['PG_PASSWORD'],
}
```

ここから下がエラー内容です

```
KeyError                                  Traceback (most recent call last)
<ipython-input-1-8ae959333cf8> in <module>
     14 pgconfig = {
     15     'host': 'db',
---> 16     'port': os.environ['PG_PORT'],
     17     'database': os.environ['PG_DATABASE'],
     18     'user': os.environ['PG_USER'],

~/opt/anaconda3/lib/python3.8/os.py in __getitem__(self, key)
    673         except KeyError:
    674             # raise KeyError with the original key value
--> 675             raise KeyError(key) from None
    676         return self.decodevalue(value)
    677 

KeyError: 'PG_PORT'
```

# 調べたこと

`os.environ` や `raise KeyError with the original key value` について調べましたが、よくわかりませんでした

# 試したこと

# 環境

| | |
|:---:|:---:|
| PC | Macbook Pro|
| OS | macOS Catalina(10.15.7) |
| Python | 3.6 |
|ライブラリ|jupyter notebook|

# 関連する問題

# 関係者

**Comment by YutaUra** [comment]
まずは、マークダウンの書き方に慣れていないと思うので、以下の用に修正します！
今後の参考にしてください！

pgconfig = {
'host': 'db',
'port': os.environ['PG_PORT'],
'database': os.environ['PG_DATABASE'],
'user': os.environ['PG_USER'],
'password': os.environ['PG_PASSWORD'],
}

だと、ただのテキストでみづらいので、 以下のように `` ``` ``で括るとその箇所をコードブロックにすることができます。さらに、`` ```python  ``というようにすると、その表示をPythonだと教えてあげることで適切な色つけをしてくれるようになります。

````
```python
pgconfig = {
    'host': 'db',
    'port': os.environ['PG_PORT'],
    'database': os.environ['PG_DATABASE'],
    'user': os.environ['PG_USER'],
    'password': os.environ['PG_PASSWORD'],
}
```
````

こんなかんじです。
```python
pgconfig = {
    'host': 'db',
    'port': os.environ['PG_PORT'],
    'database': os.environ['PG_DATABASE'],
    'user': os.environ['PG_USER'],
    'password': os.environ['PG_PASSWORD'],
}
```

あとは、関係者から @ycu-engine/engine-core を消していたんだけど、これ消しちゃうと気づけないので消さないでもらえると🙏

表は

```
| PC | Macbook Pro|
| OS | macOS Catalina(10.15.7) |
 | Python | 3.6 |
jupyter notebook
```

ではなく、

```
| | |
| :--: | :--:|
| PC | Macbook Pro|
| OS | macOS Catalina(10.15.7) |
| Python | 3.6 |
|ライブラリ|jupyter notebook|
```

とすると、以下のように表示してくれます。

| | |
| :--: | :--:|
| PC | Macbook Pro|
| OS | macOS Catalina(10.15.7) |
| Python | 3.6 |
|ライブラリ|jupyter notebook|

**Comment by YutaUra** [comment]
@mokroke 気づけなくてごめんね！
`os.environ`はPCの環境変数を格納している辞書になっているのね。
んで、`KeyError: 'PG_PORT'`ってことは、 @mokroke のPC環境に`PG_PORT`っていう環境変数が設定されてないからこういううエラーが出たんだよね。

環境変数についてわからなかったらググってみてください！

「データサイエンス100本ノック」では`Postgres`データベースを使うっていう認識でいいかな？
@mokroke のPCでPostgresを起動している必要があるんだけど、その辺の理解は大丈夫？？

それで、Potgresの方は大丈夫ってことであれば解決策をお伝えすると、「データサイエンス100本ノック」は本(?)か何かだと思うんだけど、ソースコード上にデータベースのパスワードとかをベタガキするのはあまりよろしいことではないので、ベタガキせずに環境変数から読み込むという形にしているのね。
だけど、自分で使うだけかつ公開するのではなければ、ソースコードにベタガキしても問題は無いです。
なので、以下のように変更してください。

```python
pgconfig = {
    'host': 'db',
    'port': '<Postgresのポート。多分「5432」とか>',
    'database': '<Postgresの使うデータベース名>',
    'user': '<Postgresのユーザー名>',
    'password': '<Postgresのユーザーに対応するパスワード>',
}
```

もちろん`<`, `>`は削除してくださいね！

なんか質問とかあればメンションつけてメッセージください！

**Comment by YutaUra** [comment]
@mokroke 

https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess/blob/master/docker-compose.yml#L10-L17 ここをみるにこうすればいいんじゃないかな？

```python
pgconfig = {
    'host': 'db',
    'port': '5432,
    'database': 'dsdojo_db',
    'user': 'postgres',
    'password': 'postgres12345',
}
```

**Comment by YutaUra** [comment]
一旦`os.environ で KeyError`の部分がOKなら`close`しちゃいましょう！

解決方法の部分に
- なぜ発生したのか
- どうすれば解消できるか

を残しておいてもらえると！

**Comment by YutaUra** [comment]
@mokroke

**Comment by YutaUra** [comment]
@mokroke ごめん！これまだCloseできないかな？？

**Comment by YutaUra** [comment]
@mokroke ありがとう！そしたら 解決方法 のところ記載してください！
