### ISSUE TITLE
pandasの演習問題を行いました

### ISSUE THREAD

**Issue by Kakeru-Sato** [ycu-engine/community#14]
# TL;DR
fillna()で欠損値を埋めたときその更新を反映させるためにはinplace = Trueが必要。
(df['カラム名'] = df['カラム名'].fillna(df['カラム名'].median())でも更新の反映は可能っぽい、ただ3回もカラム名打つのめんどいし間違えるから、inplace = Trueが無難な気がする）
# 内容

quiitaに転がってたpandasの演習問題を解いてpandasの理解を深めました。
pandasの基礎はだいぶしっかりできてきたように感じています。

# 参考資料

https://qiita.com/qshinichi/items/acca49e6828e58b49f67

**Comment by YutaUra** [comment]
LGTM!
