### ISSUE TITLE
Flutterで骨格推定してみました。

### ISSUE THREAD

**Issue by MatsumaruTsuyoshi** [ycu-engine/community#15]
# TL;DR

FlutterでTensorFlowLiteが使えるtfliteというプラグインを用いて骨格推定をしてみました。
基本はコピペでしたが、動作環境を整えるのが大変でした。

# 内容

↓詳細はこちら
https://matsumarudesu.com/flutter-posenet-practice/

# 参考資料

https://github.com/shaqian/flutter_tflite/tree/master/example

**Comment by YutaUra** [comment]
LGTM!
