### ISSUE TITLE
ProgateでPythonのコースを1つ終了

### ISSUE THREAD

**Issue by fujiharu0** [ycu-engine/community#17]
# TL;DR
Progateを利用してみた。
プログラムを自分で作成したのは初めてだった。
ここ２週間くらいバタバタしていたので勉強に時間をさけるようにしたい。

# 内容
Phythonのレッスンを１つ終了。
input関数を用いて、条件分岐のプログラムを作成。
str,int関数で文字と数値の変換忘れのミスと、文字を'+'でつなぎ忘れるなどしてしまっていた。

# 参考資料
特になし
※ 調べた際に参考になったものなどあれば記載してください。

**Comment by YutaUra** [comment]
LGTM!
