### ISSUE TITLE
100問ノックとDeepLearingについて学び始めました。

### ISSUE THREAD

**Issue by Kakeru-Sato** [ycu-engine/community#19]
# TL;DR
(関数名).query()の使い方や、(カラム名).str. contains(^[].*[])や(カラム名).str. contains(^[]{}-[]{}$)の使い方を学びました。
DeepLearingの方は活性化関数や行列を使った重みづけやバイアスについて学びました。
# 内容
DeepLearingの基礎(３層のニューラルネットワークの実装など)と,前回もろけんがやっていた100問ノックのpython編,DeepLearingを学ぶ上で必要なpythonの知識の復習,matplotのある程度の使い方(あんまりいい演習問題見つからなかったのでudemyの講座を見直しています)

# 参考資料
ゼロから作るDeepLaring(pythonで学ぶディープラーニングの理論と実装)
100問でわかるpython
データサイエンス100問ノック(https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess)
米国データサイエンティストがやさしく教えるデータサイエンスのためのPython講座(matplot編)(https://www.udemy.com/course/ds_for_python/learn/lecture/21513688#overview)

**Comment by YutaUra** [comment]
お疲れ様です！
