### ISSUE TITLE
Pythonを勉強した。

### ISSUE THREAD

**Issue by Rereren86** [ycu-engine/community#20]
# TL;DR
まず、Progateを用いて、Pythonについての基礎を学んだ。その後、PandasについてのYouTubeの動画を見て、Jupyter labなどの様々なその他のライブラリについて学んだ。

# 内容

# 参考資料
https://www.youtube.com/watch?v=XfoYeWCzjac&t=1754s

**Comment by YutaUra** [comment]
お疲れ様です！
