### ISSUE TITLE
Progateを進めた

### ISSUE THREAD

**Issue by fujiharu0** [ycu-engine/community#21]
# TL;DR
Progateの続きを演習した。
PhythonのⅡまで終。

# 内容
ループ関数（for,while文等）の時、無限ループしないように気を付ける
input関数(？)で入力した値は、文字型として扱われる。strにより変換必要。
プログラミング数学大事になってきそうだと思た。行列復習せな。

# 一言
とりあえずPhythonのⅤまで一周する。

**Comment by YutaUra** [comment]
お疲れさまです！
