### ISSUE TITLE
FlutterのCustomPaintを使って、骨格と角度の表示を行った。

### ISSUE THREAD

**Issue by MatsumaruTsuyoshi** [ycu-engine/community#23]
# TL;DR

懐かしの三平方の定理を使って骨格の角度を計算する関数を作って、
取り込んだ写真ごとに骨格の角度を表示するプログラムを作成した。

# 内容

https://matsumarudesu.com/flutter-posenet-angle/

# 参考資料

**Comment by YutaUra** [comment]
お疲れ様です！
