### ISSUE TITLE
Progate

### ISSUE THREAD

**Issue by fujiharu0** [ycu-engine/community#24]
# TL;DR

ProgateのPythonとりあえず1週終えた。
class、インスタンス、モジュールなどを学んだ。

# 内容

return の戻り値の部分が浅い理解な気がするから、復習していく。
Pythonを使ったWeb開発に関して学んでいきたいと今思っている。
浦さんに聞いたジャンゴの公式のサポートページの内容を学んでいく。

# 参考資料
ジャンゴの公式ページ
https://docs.djangoproject.com/ja/3.1/intro/overview/

**Comment by YutaUra** [comment]
@fujiharu0 ん、あれ？確認してみて

**Comment by fujiharu0** [comment]
> @fujiharu0 ん、あれ？確認してみて

すみません！変な形で出してそのままにしてしまっていました。直しました。

**Comment by YutaUra** [comment]
お疲れ様です！
