### ISSUE TITLE
deeplearningと機械学習の基本を始めました

### ISSUE THREAD

**Issue by Kakeru-Sato** [ycu-engine/community#25]
# TL;DR
逆伝播について学びました。乗算レイヤーの場合は、順伝播で出力される値を入れ替え、加算レイヤーの場合はそのままの値を出力。

# 内容
deep learningは順伝播、逆伝播をはじめとしさまざまなレイヤー(乗算、加算、exp、シグモイドなど)を学びました。
少しずつ行列とか微分が出てきて楽しくなってきました。
100問ノックのpython編は終わりました。
データの前処理の部分なので、復習しながら進めていこうと思います。
機械学習も少しずつ進めていますが、そっちはまだまだ序盤です。これから決定木とかの話に入るので気合入れ直して頑張ります。

# 参考資料

100問ノック(python):
https://github.com/The-Japan-DataScientist-Society/100knocks-preprocess

0から作るdeeplearning:
https://www.amazon.co.jp/ゼロから作るDeep-Learning-―Pythonで学ぶディープラーニングの理論と実装-斎藤-康毅/dp/4873117585

python機械学習プログラミング: https://www.amazon.co.jp/gp/aw/d/4295010073/ref=tmm_pap_title_0?ie=UTF8&qid=1615181358&sr=1-2-spons

**Comment by YutaUra** [comment]
お疲れ様です！
