### ISSUE TITLE
FlutterでFirebaseを使うための準備を行なった

### ISSUE THREAD

**Issue by MatsumaruTsuyoshi** [ycu-engine/community#26]
# TL;DR

Firebaseを使うとユーザー管理やデータベースの管理の手間がかなり省けそうだったので、Flutterで使うための準備を行いました。

# 内容

↓詳細はこちら
https://matsumarudesu.com/flutterfirebasecloud-firestore-prepare/

# 参考資料

Firebase公式サイト
https://firebase.google.com

Firebaseとは
https://career.levtech.jp/guide/knowhow/article/386/

**Comment by YutaUra** [comment]
お疲れ様です！
