### ISSUE TITLE
Python特にPandasについて勉強した。

### ISSUE THREAD

**Issue by Rereren86** [ycu-engine/community#28]
# TL;DR
インターネットにのっていたPythonの問題やYouTubeに乗っていたPandasの問題を解いた。

# 内容

# 参考資料
https://bdarc.net/python%E6%BC%94%E7%BF%92%E5%95%8F%E9%A1%8C15%E9%81%B8/

https://www.youtube.com/watch?v=ZQZ38rK28Gk&t=406s

**Comment by YutaUra** [comment]
お疲れ様です！
