### ISSUE TITLE
irisデータを使ってロジスティック回帰と主成分分析について学びました。

### ISSUE THREAD

**Issue by Kakeru-Sato** [ycu-engine/community#29]
# TL;DR
ロジスティック回帰はあくまで重回帰分析の一つであるから多重共線性については考慮する必要があり。基本的にVIF統計量が10を超えるか否かで判断。
主成分分析はデータの標準化→分散共分散行列を求める→固有値、固有ベクトルを求める→固有値に従って降順にソートして固有ベクトルをランクづけ。そしたら分散説明率求めて、次元削除について考えていく。
# 内容
正直本とにらめっこしてわからないとこは逐一ネットで調べて、みたいなの繰り返してたのでめっちゃ時間かかった割には学べた量は少なかったとは思う。また、いくつかの部分は知識に不安も残っているので、少しづつ解消していこうと思っている。
ただ、やっていてめちゃくちゃ楽しかった。
# 参考資料
Python機械学習プログラミング

**Comment by YutaUra** [comment]
お疲れ様です！
