### ISSUE TITLE
FFmpegを使って、Flutterで動画を画像に変換してみた

### ISSUE THREAD

**Issue by MatsumaruTsuyoshi** [ycu-engine/community#31]
# TL;DR

選択した動画をFPSに合わせて、画像に変換してみたました。
数十秒の動画だと数千枚の画像になるので、少しスマホが熱くなってしまって心配です。

# 内容

コードはGithubのレポジトリに登録してみました。
https://github.com/MatsumaruTsuyoshi/flutter_ffmpeg_video_to_image

# 参考資料

https://pub.dev/packages/flutter_ffmpeg

**Comment by YutaUra** [comment]
お疲れ様です👍
