### ISSUE TITLE
環境構築やってる途中です。

### ISSUE THREAD

**Issue by fujiharu0** [ycu-engine/community#35]
# TL;DR

Djangoについて調べた。
環境構築を、浦さんのWiki見て進めているところ。

# 内容

とりあえず環境つくらないと何もできないと気付いた。
何が必要なのか分かりずらい。
環境作ったらチュートリアルをやりながら学んでいこうと思う。

# 参考資料
VS Codeの説明：https://www.youtube.com/watch?v=lKjFKvNgLpY
Django 説明のYouTube：https://youtu.be/UY_T7j-LZ_k

**Comment by YutaUra** [comment]
がんばっていきましょう！
