### ISSUE TITLE
ボストン住宅価格データセットを使ってMLPの使い方を学びました

### ISSUE THREAD

**Issue by Kakeru-Sato** [ycu-engine/community#36]
# TL;DR
前処理としては、過学習をおこさないために標準化や正規化がマスト。最初は正規化したのもでは精度が出なかったので多項式回帰やったけど、やっぱり過学習になった。今回はそれよりは隠れ層の数や正則化のほうが有益な方法だった。

# 内容
精度を高めるために色々やりました。RobustScalerとか、正規化、標準化、あとは正則化とか多項式回帰とか。

# 参考資料

Python機械学習プログラミング
多数のブログ等

**Comment by YutaUra** [comment]
いいね〜頑張っててえらいです！
