### ISSUE TITLE
Django チュートリアル進め中

### ISSUE THREAD

**Issue by fujiharu0** [ycu-engine/community#37]
# TL;DR

学ぶための環境構築が終わったのと、少しずつ理解してきた（浦さんまじ感謝です）
Django公式のチュートリアルを進めている

# 内容

Unix系のコード？なのでコンピュータ演習の内容もろ使ってた
全部調べながら地道にやっていく

# 参考資料
WSL等の環境構築：https://zenn.dev/yuta_ura/articles/70fad750703d41
pipenvとは：https://rinatz.github.io/python-book/ch04-05-pipenv/
Django公式チュートリアル：https://docs.djangoproject.com/ja/3.1/intro/tutorial01/

**Comment by YutaUra** [comment]
お疲れ様です！
