### ISSUE TITLE
SIGNATE使い始めました

### ISSUE THREAD

**Issue by Kakeru-Sato** [ycu-engine/community#39]
# TL;DR
何度も使うもの正規化、標準化、ロバストやvifとかpcaは関数化しておくと楽だなと思いdef使って関数化しました。
# 内容
SIGNATEで血液データを使った心不全になるか否かの判定を行いました。
2値分類でしたがロジスティックがうまく利用できず前処理に問題があったようにおもいます。精度的にはランダムフォレスト使ったら出たのでランダムフォレスト使ってます。

# 参考資料
https://signate.jp

**Comment by YutaUra** [comment]
お疲れ様です！
