### ISSUE TITLE
progateでpythonを勉強しました

### ISSUE THREAD

**Issue by Kakeru-Sato** [ycu-engine/community#4]
# TL;DR

# 内容
progateに登録して、ひとまずpythonのレッスンⅤまでを一周しました。
classとか、selfとかの使い方はなんとなく掴めてきましたがまだまだ分からないところも多いので次のミーティングまでに最低もう1周やってみようと思います。
(学習したことはもう少し掴めてから再度書こうと思うのでTL;DRについては記入していません)
(こんな感じで大丈夫ですか？？笑)
# 参考資料

**Comment by YutaUra** [comment]
Goodです！
