### ISSUE TITLE
Pythonで簡単なゲームを作成している。

### ISSUE THREAD

**Issue by Rereren86** [ycu-engine/community#40]
# TL;DR
CUIで簡単なスゴロクや文字あてみたいなのを作成した。今はGUIを勉強してる。

# 参考資料

※ 調べた際に参考になったものなどあれば記載してください。

**Comment by Rereren86** [comment]
お疲れ様です。

**Comment by YutaUra** [comment]
内容聞けなくてごめん！🙇‍♂️
お疲れ様です！
> 今はGUIを勉強してる。

おぉ〜実はGUIはPythonよりもJavascriptの方が作りやすいとかってこともあるので、もしつまづいたら声かけて！
