### ISSUE TITLE
本を読んでデータ分析しました

### ISSUE THREAD

**Issue by mokroke** [ycu-engine/community#41]
# TL;DR
# 内容
engineで買っていただいたkaggleで勝つ本を読んで、コンペ用のコードを改善しました

# 参考
kaggleで勝つデータ分析の技術

※ 調べた際に参考になったものなどあれば記載してください。

**Comment by Rereren86** [comment]
サー費使えていいですね！

**Comment by YutaUra** [comment]
内容聞けなくてごめん！🙇‍♂️
お疲れ様です！
おぉ！いいですね！データ分析チャンネルの方で詳しく聞かせてくださいね！
