### ISSUE TITLE
Djangoの本進める。

### ISSUE THREAD

**Issue by fujiharu0** [ycu-engine/community#42]
入手したDjangoの本を読み進めてる。プロゲイトの復習が多かった印象。図解でまあ分かりやすいのかな？って感じです。
本に書かれてたんですけど、HTMLの知識とかもあったらやりやすいらしいから、そっちも触れた方がいいのかなって印象。
進めます。。

**Comment by Rereren86** [comment]
期待しています！

**Comment by YutaUra** [comment]
内容聞けなくてごめん！🙇‍♂️
お疲れ様です！
困った箇所とかあれば遠慮なく聞いてください！
