### ISSUE TITLE
SIGANEと統計検定2級の勉強

### ISSUE THREAD

**Issue by Kakeru-Sato** [ycu-engine/community#43]
# TL;DR
　訓練データ内で若干の過学習がある場合、その分類機をテストデータに使うと相当の過学習になってしまう。
　過学習を避けるためにロバスト、pcaを使ったが過学習は防げても精度的に出なくて精度の向上は見られなかった。

# 内容
　分類機の基本的なものと前処理の基本的なところはそうさらいした感じ。
　アンサンブル学習のハイパラをグリットサーチしていこうかな。
　統計検定は6/20.に向けて勉強中。

# 参考資料
　python機械学習プログラミング
　統計検定2級

**Comment by Rereren86** [comment]
合格してね

**Comment by YutaUra** [comment]
内容聞けなくてごめん！🙇‍♂️
お疲れ様です！
