### ISSUE TITLE
pythonの練習問題を解きました

### ISSUE THREAD

**Issue by mokroke** [ycu-engine/community#5]
# TL;DR

Pythonの基本的な文法の練習問題を10問ほど解きました。
.formatを使うと{}に文字が入れられることがわかりました。

# 内容
変数、四則演算、if文、文字列など

# 参考資料
https://gotutiyan.hatenablog.com/entry/2020/04/14/174030

**Comment by YutaUra** [comment]
お疲れ様です！いいと思います！
