### ISSUE TITLE
Flutterで動画のトリミングプラグインを実装してみました。

### ISSUE THREAD

**Issue by MatsumaruTsuyoshi** [ycu-engine/community#6]
# TL;DR

Githubに共有されているflutter-video-trimmerを実際に動かしてみました。
flutterは日本語文献が少ないので、英語の文献見ないとエラーの対処方法が分からないのがツラいです。笑

# 内容

↓詳しくは自分のブログにまとめてみました。
https://matsumarudesu.com/flutter-video-trim-prepare/

# 参考資料

↓実装してみたやつ
https://github.com/DrAchernar/flutter-video-trimmer

**Comment by YutaUra** [comment]
いいですね！
