### ISSUE TITLE
「Git使い方入門」の本で個人でGitを使うを学んだ_p1~90

### ISSUE THREAD

**Issue by fujiharu0** [ycu-engine/community#7]
# TL;DR

Gitはバージョン管理システム。変更ごとのバックアップを取ることができる。
コミュニケーションの場としてGitHubやBitbucketなどがある。

# 内容
SourceTreeをインストール。
ステージからコミットの流れ、チェックアウトの流れを理解。
重要事を作業するときは、手動でコミットの作業が必要になりそう。

# 参考資料
「わかばちゃんと学ぶ_Git使い方入門」より。（スラックにて先輩のおすすめ）

#一言
勉強に時間さけていなかった、時間をつくる

**Comment by YutaUra** [comment]
いいと思います！
