### ISSUE TITLE
pythonの環境構築

### ISSUE THREAD

**Issue by Kakeru-Sato** [ycu-engine/community#9]
# TL;DR
　

# 内容
　pythonの環境構築をしました。
何とか最後まで終えることができました。
udemyを使ってnumpyの理解の確認を行いました。

# 参考資料
https://zenn.dev/yuta_ura/articles/70fad750703d41

**Comment by YutaUra** [comment]
`numpy`は`pandas`と一緒に勉強するといいかもね！
